name: exam_cell_mobile_app
description: "Official Mobile App for the Exam Cell Dashoard"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  table_calendar: ^3.0.0
  cookie_jar: ^4.0.8
  provider: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png  

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
